Restore from database
hpi-sam/digital-fuesim-manv pull request #368
Opened 2022-05-06 16:50 UTC by ClFeSc

Closes #264 

Depends on #350 

TODOs:
- [x] A test fails

2022-05-28 20:55 UTC, Dassderdie reviewed
Not tested out yet. Only small stuff

2022-05-28 20:55 UTC, Dassderdie commented on shared/src/store/reducer-error.ts
> +// TODO: This comment is now outdated.
Just remove the `and we don't need a stack trace,` below

2022-05-29 17:33 UTC, anonym-HPI requested changes
Tested it (killing dfm container) and starting it again, seems to be working.

2022-05-29 17:33 UTC, anonym-HPI commented on backend/src/utils/user-readable-id-generator.ts
> +     * @param ids The ids to lock
```suggestion
     * @param ids to lock
```

2022-05-29 17:57 UTC, Dassderdie approved these changes

2022-05-29 17:57 UTC, anonym-HPI approved these changes

2022-05-29 17:58 UTC, merged