change HTTP and websocket port via ENV
hpi-sam/digital-fuesim-manv pull request #369
Opened 2022-05-08 18:46 UTC by anonym-HPI

please check it, possibly by building docker locally, the ENV is HTTP_PORT

HTTPS comes with another PR

2022-05-12 12:47 UTC, ClFeSc requested changes

2022-05-12 12:47 UTC, ClFeSc commented on frontend/src/environments/environment.deployment.ts
> +    websocketPort: ((window as any).env.websocketPort as number) || 80,
It could be better to use a JSON file instead of a function and load the values from this file (thanks to @Dassderdie for the suggestion).

2022-05-12 16:00 UTC, anonym-HPI commented
Code is active on https://dev.fuesim-manv.de, seems to work

Only case that is not covered is:
location.protocol is not a number and it is not http with port 80 or https with port 443.

2022-05-12 17:29 UTC, ClFeSc commented on frontend/src/environments/environment.deployment.ts
> +        Number(window.location.port) || window.location.protocol === 'https:'
Why not `Number.parseInt`?

2022-05-15 13:52 UTC, ClFeSc commented on frontend/src/environments/environment.deployment.ts
> +        Number(window.location.port) || window.location.protocol === 'https:'
@Dassderdie What do you think here?

2022-05-15 13:57 UTC, ClFeSc commented on frontend/src/environments/environment.deployment.ts
> +        Number(window.location.port) || window.location.protocol === 'https:'
I'm happy now.

2022-05-15 13:57 UTC, ClFeSc approved these changes

2022-05-15 14:07 UTC, merged