enable SSL via ENVs
hpi-sam/digital-fuesim-manv pull request #379
Opened 2022-05-12 20:02 UTC by anonym-HPI

TODO:
- disallow http traffic and redirect when ssl is enabled (maybe via ENV enabled by default)
- ssl header hardening (disabling by default, probably but encouring it but warning, only enabling it after https works flawlessly even with docker restarts - after it http will not be possible on this domain for a year, without getting into every browser settings of every browser that visitted this domain)

needs https://github.com/hpi-sam/digital-fuesim-manv/pull/369

2022-06-08 09:50 UTC, ClFeSc requested changes

2022-06-08 10:26 UTC, anonym-HPI commented on docker/Dockerfile
> +RUN cd / && /acme.sh --install --config-home /ssl/acme.sh/config --cert-home /ssl/acme.sh/certs && \
I have to, as the acme.sh script otherwise not works properly.

2022-06-09 08:31 UTC, ClFeSc commented on docker/cron-renew-session-ticket
> +curl https://${DOMAIN} > /dev/null 2>&1
Please make clear that this is an error in nginx, then I'm happy with it.

2022-06-10 09:22 UTC, ClFeSc reviewed
Just the two TODO comments remaining. Any feedback on them would be nice. Otherwise looks good. I haven't tested it, though.

2022-07-29 08:31 UTC, ClFeSc commented
> Just the two TODO comments remaining. Any feedback on them would be nice. Otherwise looks good. I haven't tested it, though.

@anonym-HPI Still no updates?

2022-07-29 10:20 UTC, anonym-HPI commented
@ClFeSc what about putting everything important in something like /dfm or /data or /persistent-data or ... ?

2022-07-29 13:39 UTC, ClFeSc commented on docker/Dockerfile
> +# /ssl includes certs and acme.sh config - mount $PERISTENT_DATA_PATH as a volume for persistency
Update comment with new env

2022-07-29 13:39 UTC, ClFeSc commented on docker/nginx/certs
> +# empty gets build in docker-entrypoint.sh
What is empty?

2022-07-30 08:44 UTC, ClFeSc commented on docker/Dockerfile
> +# /ssl includes certs and acme.sh config - mount $PERISTENT_DATA_PATH as a volume for persistency
@anonym-HPI Unfortunately, you've missed `DFM_` in the env name twice in this line.

2022-07-30 12:56 UTC, ClFeSc commented on docker/Dockerfile
> +# /ssl includes certs and acme.sh config - mount $PERISTENT_DATA_PATH as a volume for persistency
@anonym-HPI Unfortunately, now you've lost the `$`.

2022-07-30 14:22 UTC, anonym-HPI commented
@ClFeSc waiting for final approval

2022-07-31 08:25 UTC, ClFeSc approved these changes

2022-07-31 08:25 UTC, merged