implementing main functionalities of the eoc
hpi-sam/digital-fuesim-manv pull request #393
Opened 2022-05-23 11:20 UTC by hpistudent72

2022-05-26 20:13 UTC, Dassderdie approved these changes
I applied my feedback in 4359a328e45c567f1a2747858ef23c61d460f9de
@hpistudent72 please have a look at it.

As already discussed - the collapse stuff could be added back later when adding the log.

2022-05-27 09:01 UTC, ClFeSc requested changes
Mostly minor things and one thing too big for now.

What is up with the file `shared/src/store/action-reducers/utils/get-template.ts`?

2022-05-27 09:10 UTC, ClFeSc requested changes
Another problem: I can alarm a group to a deleted transfer point when it's the previously selected target.

2022-05-27 09:14 UTC, ClFeSc commented
See also #404 in this context.

2022-05-27 10:57 UTC, Dassderdie commented on frontend/src/app/pages/exercises/exercise/shared/emergency-operations-center/send-alarm-group-interface/send-alarm-group-interface.component.html
> +                [disabled]="!transferPoints.length"
yes

2022-05-27 10:58 UTC, Dassderdie commented on frontend/src/app/pages/exercises/exercise/shared/emergency-operations-center/send-alarm-group-interface/send-alarm-group-interface.component.ts
> +            if (requests.every((request) => request.success)) {
The `proposeAction` should already show an error automatically.

2022-05-27 10:59 UTC, Dassderdie commented on shared/src/models/utils/start-points.ts
> +export class TransferStartPoint {
Probably a good idea: `StartPoint`

2022-05-27 11:02 UTC, Dassderdie commented
> Another problem: I can alarm a group to a deleted transfer point when it's the previously selected target.

I wanted to display invalid transferPoints in `app-transfer-point-name` with `text-danger` -> there would be at least a visual indicator for it. (#358)
We could also check whether the transferPoint exists before alarming the group (getStateSnapshot).

2022-05-27 13:24 UTC, hpistudent72 commented on frontend/src/app/pages/exercises/exercise/shared/emergency-operations-center/send-alarm-group-interface/send-alarm-group-interface.component.ts
> +            if (requests.every((request) => request.success)) {
We get an error if one action fails. This also fixes itself when we take care of https://github.com/hpi-sam/digital-fuesim-manv/issues/406

2022-05-27 13:25 UTC, hpistudent72 commented on frontend/src/app/pages/exercises/exercise/shared/emergency-operations-center/send-alarm-group-interface/send-alarm-group-interface.component.ts
> +        // TODO: Refactor this into one action (uuid generation is currently not possible in the reducer)
Added an Issue for this https://github.com/hpi-sam/digital-fuesim-manv/issues/406

2022-05-27 20:52 UTC, ClFeSc reviewed
Should

> > Another problem: I can alarm a group to a deleted transfer point when it's the previously selected target.
> 
> I wanted to display invalid transferPoints in `app-transfer-point-name` with `text-danger` -> there would be at least a visual indicator for it. (#358) We could also check whether the transferPoint exists before alarming the group (getStateSnapshot).

be fixed in this PR? Otherwise, I'm happy with it.

2022-05-28 14:30 UTC, Dassderdie commented
> Should
> 
> > > Another problem: I can alarm a group to a deleted transfer point when it's the previously selected target.
> > 
> > 
> > I wanted to display invalid transferPoints in `app-transfer-point-name` with `text-danger` -> there would be at least a visual indicator for it. (#358) We could also check whether the transferPoint exists before alarming the group (getStateSnapshot).
> 
> be fixed in this PR? Otherwise, I'm happy with it.

This will be done in another PR.

2022-05-28 14:39 UTC, merged