Add secure http handler
hpi-sam/digital-fuesim-manv pull request #440
Opened 2022-06-08 09:48 UTC by ClFeSc

Closes #430

2022-06-09 08:39 UTC, ClFeSc commented
I don't think I can do the better typing, so this should be ready for review.

2022-06-09 09:57 UTC, Dassderdie commented on backend/src/exercise/http-handler/secure-http.ts
> +import type { Express, Request } from 'express';
```suggestion
import type { Express, Request as ExpressRequest } from 'express';
```
And rename `Request` to `ExpressRequest` in the rest of the file.

2022-06-09 10:06 UTC, Dassderdie commented on backend/src/exercise/http-server.ts
> +        );
Currently, you replace the whole express API to proxy it. What about only wrapping the handler like this:
```ts
        app.get(
            '/api/health',
            secureHttp((req, res) => {
                const response = getHealth();
                res.statusCode = response.statusCode;
                res.send(response.body);
            })
        );
```

2022-07-16 23:04 UTC, Dassderdie requested changes
I think this is the only way to infer the correct type for `req`...

2022-07-16 23:04 UTC, Dassderdie commented on backend/src/exercise/http-server.ts
> +        );
```suggestion
        app.get('/api/health', (req) => secureHttp(getHealth));

        app.post('/api/exercise', (req) =>
            secureHttp(async () => postExercise(databaseService, req.body))
        );

        app.get('/api/exercise/:exerciseId', (req) =>
            secureHttp(() => getExercise(req.params.exerciseId))
        );

        app.delete('/api/exercise/:exerciseId', (req) =>
            secureHttp(async () => deleteExercise(req.params.exerciseId))
        );

        app.get('/api/exercise/:exerciseId/history', (req) =>
            secureHttp(async () => getExerciseHistory(req.params.exerciseId))
        );
```

2022-07-16 23:04 UTC, Dassderdie commented on backend/src/exercise/http-handler/secure-http.ts
> +            response = await operation(req);
```suggestion
export function secureHttp(
    operation: () =>
        | HttpResponse<object | undefined>
        | Promise<HttpResponse<object | undefined>>
): (req: ExpressRequest, res: ExpressResponse) => Promise<void> {
    return async (_req: ExpressRequest, res: ExpressResponse) => {
        let response: HttpResponse<any>;
        try {
            response = await operation();
```

2022-07-23 14:18 UTC, Dassderdie commented
@ClFeSc the pipeline is failing - code wise I'm ok with it.

2022-07-23 17:46 UTC, ClFeSc commented
@Dassderdie It should work now...

2022-07-23 20:48 UTC, Dassderdie approved these changes
Still not tested, but code lgtm.

2022-07-23 20:48 UTC, merged