Keep all actions
hpi-sam/digital-fuesim-manv pull request #468
Opened 2022-07-20 16:13 UTC by ClFeSc

Closes #455

2022-07-21 12:28 UTC, Dassderdie commented on backend/src/fuesim-server.spec.ts
> +                return Promise.resolve(entities);
```suggestion
                return entities;
```
The async function automatically converts this to a promise -> the Promise.resolve is unnecessary

2022-07-25 11:50 UTC, ClFeSc commented
@Dassderdie I've renamed the variable in the `ExerciseWrapper` and added a comment for the test (and also fixed a logic error).

2022-07-25 12:25 UTC, Dassderdie requested changes

2022-07-25 12:25 UTC, Dassderdie commented on backend/src/exercise/exercise-wrapper.ts
> +        this.temporaryActionHistory.splice(0, this.numberOfActionsToBeSaved);
Shouldn't this be 
```ts
this.temporaryActionHistory.splice(0, this.numberOfActionsToBeSaved);
this._changedSinceSave = this.temporaryActionHistory.length > 0;
```
?

2022-07-25 12:29 UTC, Dassderdie approved these changes
Code lgtm.

2022-07-25 12:34 UTC, merged