Throw `ReducerError` for when starting/pausing an exercise
hpi-sam/digital-fuesim-manv pull request #471
Opened 2022-07-22 20:10 UTC by ClFeSc

Closes #465

2022-07-24 16:22 UTC, Dassderdie reviewed
Either we merge this now and add #466 in another pull request or do it with this one here.

2022-07-24 16:22 UTC, Dassderdie commented on shared/src/store/action-reducers/exercise.ts
> +            if (!lastEntry || lastEntry.status === 'paused') {
There is `Exercise.getStatus()`.

But this will be irrelevant when #466 is done.

2022-07-24 16:22 UTC, Dassderdie commented on shared/src/store/reduce-exercise-state.spec.ts
> +    });
Missing test: `It correctly starts and stops an exercise`.

2022-07-24 17:38 UTC, ClFeSc commented
> Either we merge this now and add #466 in another pull request or do it with this one here.

I'd need #476 for #466. We can wait here until it's there and do it all in this PR. We can also merge this, and then open a new one.

2022-07-27 10:16 UTC, Dassderdie requested changes

2022-07-27 10:16 UTC, Dassderdie commented on backend/src/exercise/exercise-wrapper.spec.ts
> +                { type: '[Exercise] Start', timestamp: 0 },
```suggestion
                { type: '[Exercise] Start' },
```

2022-07-27 10:16 UTC, Dassderdie commented on backend/src/exercise/exercise-wrapper.spec.ts
>                  { type: '[Exercise] Pause', timestamp: 0 },
```suggestion
                { type: '[Exercise] Pause' },
```

2022-07-27 10:16 UTC, Dassderdie commented on frontend/src/app/core/api.service.ts
> +    public async proposeAction(action: ExerciseAction, optimistic = false) {
Good catch!

2022-07-27 10:16 UTC, Dassderdie commented on shared/src/state.ts
> +        // );
```suggestion
```

2022-07-27 10:16 UTC, Dassderdie commented on shared/src/state.ts
> +    static getStatus(state: ExerciseState): ExerciseStatus {
I would probably remove this function.

2022-07-27 10:16 UTC, Dassderdie commented on shared/src/store/reduce-exercise-state.spec.ts
> +                timestamp: 0,
```suggestion
```

2022-07-27 10:16 UTC, Dassderdie commented on shared/src/store/reduce-exercise-state.spec.ts
> +                timestamp: 0,
```suggestion
```

2022-07-27 10:16 UTC, Dassderdie commented on shared/src/store/reduce-exercise-state.spec.ts
> +                expected: 'notStarted' | 'paused' | 'running'
```suggestion
                expected: ExerciseStatus
```

2022-07-27 12:48 UTC, Dassderdie commented on backend/src/database/state-migrations/3-remove-state-history.ts
> +import type { Action } from 'digital-fuesim-manv-shared/dist/store/action-reducer';
This has been fixed by 8375560d88639009f7b8b680de51f4b514e53374 in #473

2022-07-27 12:51 UTC, Dassderdie approved these changes
LGTM - I expect #473 to be merged first -> The `dist/...` can be removed from the Action import

2022-07-27 13:29 UTC, Dassderdie commented
TODO: remove all the logic for nondeterministic actions - either in here or on a new branch

2022-07-28 08:24 UTC, ClFeSc commented
> TODO: remove all the logic for nondeterministic actions - either in here or on a new branch

I'd say in a new branch.

@Dassderdie Can this be merged then?

2022-07-28 08:38 UTC, ClFeSc commented
> TODO: remove all the logic for nondeterministic actions - either in here or on a new branch

See #498

2022-07-28 08:45 UTC, merged