vehicle image changing depending on number of patients loaded
hpi-sam/digital-fuesim-manv pull request #501
Opened 2022-07-29 00:12 UTC by anonym-HPI

fix https://github.com/hpi-sam/digital-fuesim-manv/issues/500

2022-07-29 08:28 UTC, ClFeSc requested changes
@anonym-HPI Does this work for you locally? I can't start the backend with `ReferenceError: Cannot access 'Vehicle' before initialization`, but this may be caused by my local setup.

Edit: The CI would like to agree with me that this does not work.

2022-07-29 08:28 UTC, ClFeSc commented on shared/src/models/vehicle-template.ts
>      public readonly image: ImageProperties;
This can, in contrast to the comment, never be an array.

2022-07-29 08:28 UTC, ClFeSc commented on shared/src/models/vehicle-template.ts
> +    public readonly imagesPatientsLoaded?: ImageProperties[];
Prefer `null` over `undefined` for new code (@Dassderdie I think we've come to that conclusion?):

```suggestion
    public readonly imagesPatientsLoaded: ImageProperties[] | null;
```

The validators should work the same, I've not tested it, though.

2022-07-29 08:28 UTC, ClFeSc commented on shared/src/models/vehicle-template.ts
> +            throw new ReducerError(
I'm not sure a `ReducerError` is the best choice here. @Dassderdie What do you think?

2022-07-29 08:28 UTC, ClFeSc commented on shared/src/models/vehicle-template.ts
> +                `vehicle was tried to be created, but imagesPatientsLoaded.length is not equal to patientCapacity`
```suggestion
                `Cannot create a vehicle with ${imagesPatientsLoaded.length} images and a capacity of ${patientCapacity}.`
```

2022-07-29 08:28 UTC, ClFeSc commented on shared/src/models/vehicle.ts
> +            );
Same comments as in the template.

2022-07-29 08:28 UTC, ClFeSc commented on shared/src/store/action-reducers/vehicle.ts
> +                        `vehicle was tried to be unloaed while not having correct imagesPatientsLoaded`
```suggestion
                        `vehicle was tried to be loaded while not having correct imagesPatientsLoaded`
```

2022-07-29 08:28 UTC, ClFeSc commented on shared/src/store/action-reducers/vehicle.ts
> +                    // TODO: why needing "!"" at the end?
Because TS has no idea that this element exists. It can't relate the check above to here. You can use an extra `const` for this.

2022-09-29 21:02 UTC, Dassderdie commented
This won't be merged anytime soon, I guess. I, therefore, close this PR but mention it in the corresponding issue #500 .

2022-09-29 21:02 UTC, closed without merging