Add UI for `VehicleTemplate` editing
hpi-sam/digital-fuesim-manv pull request #589
Opened 2022-12-26 19:03 UTC by ClFeSc

Closes #588

2025-04-10 12:28 UTC, lukasrad02 requested changes

2025-04-10 12:36 UTC, ClFeSc commented on frontend/src/app/pages/exercises/exercise/shared/editor-panel/create-vehicle-template-modal/create-vehicle-template-modal.component.ts
> +        private readonly exerciseService: ExerciseService
I don't know, to be honest. The `exerciseService` is `private` because it can be, but out `NgbActiveModal`s are `public` everywhere we use them.

2025-04-10 12:39 UTC, lukasrad02 commented on frontend/src/app/pages/exercises/exercise/shared/editor-panel/create-vehicle-template-modal/open-create-vehicle-template-modal.ts
> +    ngbModalService.open(CreateVehicleTemplateModalComponent);
Would you mind using an a bit larger size (maybe `lg`) for both the create and edit modal?

When editing a more complex template (e.g. GW San) with lots of material and personnel, one has to scroll down quite a bit to reach the buttons, as only two items fit next to each other.

2025-04-10 12:43 UTC, lukasrad02 commented on frontend/src/app/pages/exercises/exercise/shared/editor-panel/create-vehicle-template-modal/create-vehicle-template-modal.component.ts
> +        private readonly exerciseService: ExerciseService
> `NgbActiveModals` are public everywhere we use them

They only have to be public if you want to use them from the template (e.g. calling `activeModal.close()` directly in an event handler). I think some people just copied the `public` modifier from such a component and never changed it.

2025-04-10 12:48 UTC, ClFeSc commented on frontend/src/app/pages/exercises/exercise/shared/editor-panel/create-vehicle-template-modal/create-vehicle-template-modal.component.ts
> +        private readonly exerciseService: ExerciseService
Ah, I see. Will make it `private`.

2025-04-11 10:13 UTC, ClFeSc commented on shared/src/store/action-reducers/vehicle-templates.ts
> +                // Delete every alarm group that uses this template
I've tried to rework it in a way that only the deleted vehicle gets deleted from the alarm groups (and also have a confirmation beforehand). But this is broken for some reason. The way I've implemented the reducer successfully removes the vehicle template with id `id` from all alarm groups in the backend. In the frontend, however, it removes exactly all vehicles that are *not* `id`, thus breaking many things. Reloading fixes this as the backend never had the issue in the first place. I've pushed `backend-after.json` and `frontend-after.json` files showing the respective states right after applying the remove vehicle template action.

2025-04-11 17:41 UTC, ClFeSc commented on shared/src/store/action-reducers/vehicle-templates.ts
> +                // Delete every alarm group that uses this template
This should be working. I think I had the same problem as when switching branches with the new `vite` approach from `angular`: It did not update the `shared` package correctly in the `frontend`, and the version it kept was the one where I had accidentally swapped the condition around. And then it never updated...

Btw: `vite` is a great piece of software: https://github.com/hpi-sam/digital-fuesim-manv/actions/runs/14408881083/job/40411947000?pr=589#step:7:9

2025-04-12 07:00 UTC, lukasrad02 requested changes

2025-04-12 07:01 UTC, lukasrad02 commented
Apart from the one change request above, this PR looks fine now

2025-04-12 09:36 UTC, ClFeSc commented on frontend/src/app/pages/exercises/exercise/shared/editor-panel/edit-vehicle-template-modal/edit-vehicle-template-modal.component.ts
> +        public readonly activeModal: NgbActiveModal,
Changed it.

2025-04-12 14:07 UTC, lukasrad02 approved these changes

2025-04-12 14:10 UTC, lukasrad02 commented
I've noticed that you merged #522 with a merge commit. The previous PRs have all been squashed.

I don't have a strong opinion on this, but would prefer continuing squash merging.

2025-04-12 15:41 UTC, merged

2025-04-12 15:45 UTC, ClFeSc commented
> I've noticed that you merged #522 with a merge commit. The previous PRs have all been squashed.
> 
> I don't have a strong opinion on this, but would prefer continuing squash merging.

Ah, missed that. I've had to look up which merge strategy was used in another repo before and must've just kept my assumption without checking again. I've used a squash merge here. In repos where we don't usually rebase I like this more than adding all those commits to the default branch.